Edit Terranode.de profile
terra-project/validator-profiles pull request #81
Opened 2021-03-03 00:02 UTC by bitradioUwe

2021-03-03 01:33 UTC, bitradioUwe commented
Would be great if you can update it. Thanks a lot.
Uwe

2021-03-29 07:54 UTC, hanjukim commented
Your website is empty.

2021-03-29 18:42 UTC, hanjukim requested changes

2021-03-29 18:42 UTC, hanjukim commented on validators/terravaloper1sz53f8emf76s6gs2u7gdhsr7v0jz4lql3x6nqr/profile.json
> +    "contact": { // contact info for delegators / outreach
Comments are not available in JSON.

2021-03-29 18:42 UTC, hanjukim commented on validators/terravaloper1sz53f8emf76s6gs2u7gdhsr7v0jz4lql3x6nqr/README.md
> +
websites are empty

2021-03-29 18:42 UTC, hanjukim commented on template/profile.json
> +---
This is not a json file

2021-04-12 02:13 UTC, closed without merging